export const heroItems = [
	{
		src: "/fishing.jpg",
		alt: "Fishing",
		title: "Fishing",
		percent: 100,
		positionX: "85%",
		positionY: "45%",
	},
	{
		src: "/medical.jpg",
		alt: "Medical",
		title: "Medical",
		percent: 100,
		positionX: "5%",
		positionY: "0%",
	},
	{
		src: "/emergency.jpg",
		alt: "Emergency",
		title: "Emergency",
		percent: 100,
		positionX: "0%",
		positionY: "45%",
	},
	{
		src: "/animal.jpg",
		alt: "Animal",
		title: "Animal",
		percent: 100,
		positionX: "5%",
		positionY: "90%",
	},
	{
		src: "/business.jpg",
		alt: "Business",
		title: "Business",
		percent: 100,
		positionX: "81%",
		positionY: "0%",
	},
	{
		src: "/education.webp",
		alt: "Education",
		title: "Education",
		percent: 100,
		positionX: "81%",
		positionY: "90%",
	},
];